#!/usr/bin/env bash
# Generated by Chock. Blocks git commit/push --no-verify or -n flag tokens.
# Best-effort guard; bypasses are possible via aliases, subshells, or non-standard clients.
set -eu

is_git_commit_or_push=0
subcommand=""

for arg in "$@"; do
    case "$arg" in
        git) ;;
        commit|push)
            is_git_commit_or_push=1
            subcommand="$arg"
            ;;
    esac
done

if [[ "$is_git_commit_or_push" -eq 0 ]]; then
    exit 0
fi

has_n=0
for arg in "$@"; do
    if [[ "$arg" == "--no-verify" ]]; then
        has_n=1
    elif [[ "$arg" == "-n" ]]; then
        has_n=1
    elif [[ "$arg" =~ ^-[^-] ]]; then
        # Combined short flags: block if the token contains 'n' (e.g. -nm).
        if [[ "$arg" == *n* ]]; then
            has_n=1
        fi
    fi
done

if [[ "$has_n" -eq 1 ]]; then
    echo "BLOCKED: git $subcommand --no-verify is not allowed. Fix the hook failure instead." >&2
    exit 1
fi

exit 0
